protected/models/Event.php
<?php

/**
 * This is the model class for table "event".
 *
 * The followings are the available columns in table 'event':
 * @property integer $id
 * @property string $start_date
 * @property string $end_date
 * @property integer $instance_id
 * @property string $completed_in
 * @property array $archetypes
 * @property string $notes
 *
 * The followings are the available model relations:
 * @property Instance $instance
 * @property Loot[] $loots
 * @property Member[] $members
 */
class Event extends CActiveRecord {
    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Event the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'event';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        return array(
            array('start_date, instance_id, archetypes', 'required'),
            array('instance_id', 'numerical', 'integerOnly' => true),
            array('end_date, completed_in, notes, is_private', 'safe'),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('id, start_date, end_date, instance_id, completed_in, notes', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        return array(
            'loots' => array(self::MANY_MANY, 'Loot', 'event_loot(event_id, loot_id)'),
            'members' => array(self::MANY_MANY, 'Member', 'event_member(event_id, member_id)'),
            'instance' => array(self::BELONGS_TO, 'Instance', 'instance_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'instance_id' => 'Instance',
            'completed_in' => 'Completed In',
            'notes' => 'Notes',
            'is_private' => 'Is event public or private?',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search() {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('start_date', $this->start_date, true);
        $criteria->compare('end_date', $this->end_date, true);
        $criteria->compare('instance_id', $this->instance_id);
        $criteria->compare('completed_in', $this->completed_in, true);
        $criteria->compare('notes', $this->notes, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array(
            'datetimebehavior' => array('class' => 'ext.behaviors.EDatetimeBehavior'),
        );
    }

    public function scopes() {
        return array(
            'available' => array(
                'condition' => 'start_date > DATE("NOW", "+15 MINUTE")',
                'limit' => 3,
                'order' => 'start_date ASC'
            )
        );
    }

    public function defaultScope() {
        return array(
            'order' => 'start_date DESC'
        );
    }

    public function beforeSave() {
        $this->archetypes = json_encode($this->archetypes);
        return parent::beforeSave();
    }

    public function afterFind() {
        $this->archetypes = json_decode($this->archetypes, true);
        return parent::afterFind();
    }

    public function getMembersSignedByArchetype($archetype) {
        return EventMember::model()->countByAttributes(array(
            'event_id' => $this->id,
            'archetype' => $archetype,
        ));
    }

    public function getArchetypeMembersSigned() {
        $cr = new CDbCriteria();
        $cr->select = 'archetype, COUNT(event_id) AS cnt';
        $cr->condition = 'event_id = :event';
        $cr->params = array(':event' => $this->id);
        $cr->group = 'archetype';
        return CHtml::listData(EventMember::model()->findAll($cr), 'archetype', 'cnt');
    }

    public function getBackups() {
        return EventMember::model()->countByAttributes(array(
            'event_id' => $this->id,
            'archetype' => Archetype::ARCHETYPE_BACKUP,
        ));
    }

    public function meetsRequirements() {
        $member = Yii::app()->user->member;
        return ($member->avg_weapon_ql >= $this->instance->min_weapon_ql) &&
        ($member->avg_talisman_ql >= $this->instance->min_talisman_ql) &&
        ($member->avg_glyph_ql >= $this->instance->min_glyph_ql);

    }

    public function isUserInEvent() {
        return EventMember::model()->findByPk(array(
            'event_id' => $this->id,
            'member_id' => Yii::app()->user->member->id
        ));
    }

    public function removeAllMembers() {
        foreach ($this->members as $member)
            EventMember::model()->findByPk(array(
                'event_id' => $this->id,
                'member_id' => $member->id,
            ))->delete();
        return;
    }
}

protected/controllers/EventController.php
<?php

class EventController extends Controller {
    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete', 'export'),
                'expression' => '!Yii::app()->user->isGuest && Yii::app()->user->member->role == Role::ROLE_ADMIN',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $event = $this->loadModel($id);
        $member = new EventMember('search');
        $member->event_id = $id;

        $this->render('view', array(
            'event' => $event,
            'model' => $member,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        Yii::app()->clientScript->registerCoreScript('jquery');
        Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/bootstrap-datetimepicker.min.js');
        Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/datetimepicker.css');

        $model = new Event;

        if (isset($_POST['Event'])) {
            if (isset($_POST['repeat'])) {
                for ($i = 0; $i < $_POST['number']; ++$i) {
                    $model->attributes = $_POST['Event'];
                    $startDate = new DateTime($model->start_date);
                    $startDate->add(new DateInterval("P{$i}{$_POST['period']}"));
                    $endDate = new DateTime($model->end_date);
                    $endDate->add(new DateInterval("P{$i}{$_POST['period']}"));
                    $model->start_date = $startDate->format('Y-m-d H:i:s');
                    $model->end_date = $endDate->format('Y-m-d H:i:s');
                    $archetypes = array();
                    foreach ($_POST['Arch'] as $arch)
                        $archetypes[$arch['key']] = $arch['count'];
                    $model->archetypes = $archetypes;
                    if ($model->save()) {
                        if (isset($_POST['event_members'])) {
                            foreach ($_POST['event_members'] as $memberID) {
                                $member = Member::model()->findByPk($memberID);
                                $m = new EventMember();
                                $m->event_id = $model->id;
                                $m->member_id = $memberID;
                                $m->archetype = $member->main_archetype;
                                $m->date_signed = date('Y-m-d H:i:s');
                                $m->save();
                            }
                        }
                        $model = new Event;
                    }
                }
                $this->redirect(array('admin'));
            } else {
                $model->attributes = $_POST['Event'];
                $archetypes = array();
                foreach ($_POST['Arch'] as $arch)
                    $archetypes[$arch['key']] = $arch['count'];
                $model->archetypes = $archetypes;
                if ($model->save()) {
                    if (isset($_POST['event_members'])) {
                        foreach ($_POST['event_members'] as $memberID) {
                            $member = Member::model()->findByPk($memberID);
                            $m = new EventMember();
                            $m->event_id = $model->id;
                            $m->member_id = $memberID;
                            $m->archetype = $member->main_archetype;
                            $m->date_signed = date('Y-m-d H:i:s');
                            $m->save();
                        }
                    }
                    $this->redirect(array('view', 'id' => $model->id));
                }
            }
        }

        $this->render('create', array(
            'model' => $model,
            'archetypes' => Archetype::getArray(),
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        Yii::app()->clientScript->registerCoreScript('jquery');
        Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/bootstrap-datetimepicker.min.js');
        Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/datetimepicker.css');

        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Event'])) {
            $model->attributes = $_POST['Event'];
            $archetypes = array();
            foreach ($_POST['Arch'] as $arch)
                $archetypes[$arch['key']] = $arch['count'];
            $model->archetypes = $archetypes;
            if ($model->save()) {
                if (isset($_POST['event_members'])) {
                    $model->removeAllMembers();
                    foreach ($_POST['event_members'] as $memberID) {
                        $member = Member::model()->findByPk($memberID);
                        $m = new EventMember();
                        $m->event_id = $model->id;
                        $m->member_id = $memberID;
                        $m->archetype = $member->main_archetype;
                        $m->date_signed = date('Y-m-d H:i:s');
                        $m->save();
                    }
                }
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
            'archetypes' => Archetype::getArray(),
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Event');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Event('search');
        $model->unsetAttributes();
        if (isset($_GET['Event']))
            $model->attributes = $_GET['Event'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

	public function actionExport($event) {
		$em = new EventMember();
		$em->event_id = $event;
		$this->widget('application.extensions.phpexcel.EExcelView', array(
			'dataProvider'=> $em->search(),
			'grid_mode'=>'export',
			'title'=>'Signed up members',
			'filename'=>'members',
			'stream'=>true,
			'exportType'=>'Excel2007',
			'columns'=>array(
				array (
					'name' => 'member.name',
					'htmlOptions' => array('style' => 'font-weight: bold;')
				),
				array(
					'type' => 'raw',
					'name' => 'archetype',
					'value' => 'CHtml::tag("span", array("class" => "label " . Archetype::cssClass($data->archetype)), Archetype::toText($data->archetype))',
				),
				'notes',
				array(
					'name' => 'date_signed',
					'value' => 'Yii::app()->dateFormatter->formatDateTime(strtotime($data->date_signed))'
				),
			),
		));

		Yii::app()->end();
	}

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id) {
        $model = Event::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'event-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/views/event/_form.php
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id' => 'event-form',
    'enableAjaxValidation' => false,
)); ?>

<?php echo $form->errorSummary($model); ?>

<div class="customise-panel" id="timer-panel">
    <?php echo $form->labelEx($model, 'start_date'); ?>
    <div id="datetimepicker-start_date" class="input-append date" data-date-format="dd-mm-yyyy hh:ii">
        <?php echo $form->textField($model, 'start_date', array('readonly' => true)); ?>
        <span class="add-on"><i class="icon-th"></i></span>
    </div>
</div>

<div class="customise-panel" id="timer-panel">
    <?php echo $form->labelEx($model, 'end_date'); ?>
    <div id="datetimepicker-end_date" class="input-append date" data-date-format="dd-mm-yyyy hh:ii">
        <?php echo $form->textField($model, 'end_date', array('readonly' => true)); ?>
        <span class="add-on"><i class="icon-th"></i></span>
    </div>
</div>
<?php if ($model->isNewRecord) : ?>
    <div class="customise-panel">
        <?php echo CHtml::label('Repeat event', 'repeat'); ?>
        <?php echo CHtml::checkBox('repeat', false, array('id' => 'event-repeat')); ?>
    </div>

    <div id="event-repeat-period" style="display: none;">
        <?php echo CHtml::label('Period', 'period'); ?>
        <?php echo CHtml::dropDownList('period', '', array('W' => 'Weekly', 'M' => 'Monthly')); ?>
        <?php echo CHtml::label('Number of repetitions', 'number'); ?>
        <?php echo CHtml::textField('number'); ?>
    </div>

    <hr>
<?php endif; ?>
<?php echo $form->dropDownListRow($model, 'instance_id', CHtml::listData(Instance::model()->findAll(), 'id', 'name'), array('class' => 'span5')); ?>

<?php echo $form->dropDownListRow($model, 'is_private', array(0 => 'Public', 1 => 'Private'), array('class' => 'span5')); ?>
<fieldset id="public">
    <legend>Classes</legend>
    <?php foreach ($archetypes as $key => $arch) : ?>
        <?php if ($key != Archetype::ARCHETYPE_BACKUP) : ?>
            <?php echo CHtml::label($arch, "Arch[{$arch}][count]"); ?>
            <?php echo CHtml::hiddenField("Arch[{$arch}][key]", $key); ?>
            <?php echo CHtml::textField("Arch[{$arch}][count]", $model->archetypes[$key], array('class' => 'span2')); ?>
        <?php endif; ?>
    <?php endforeach; ?>
</fieldset>
<fieldset id="private" style="display:none; ">
    <legend>Members</legend>
    <p class="hint">Select the members that will be part of this event. The event will only be visible to them and
        officers.</p>
    <?php $this->widget('ext.select2.ESelect2', array(
        'name' => 'event_members[]',
        'value' => $model->members,
        'data' => CHtml::listData(Member::model()->findAll(), 'id', 'name'),
        'htmlOptions' => array('multiple' => 'multiple', 'style' => 'width: 500px;')
    )); ?>
</fieldset>

<hr>

<?php echo $form->textAreaRow($model, 'notes', array('rows' => 6, 'cols' => 50, 'class' => 'span8')); ?>

<div class="form-actions">
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type' => 'primary',
        'label' => $model->isNewRecord ? 'Create' : 'Save',
    )); ?>
</div>

<?php $this->endWidget(); ?>
<script>
    $(function () {
        $('#datetimepicker-start_date, #datetimepicker-end_date').datetimepicker({
            autoClose: true,
            minuteStep: 15
        });

        $('#Event_is_private').change(function () {
                $("fieldset#private").toggle();
                $("fieldset#public").toggle();
            }
        );

        $('#event-repeat').change(function () {
            if ($(this).is(":checked")) {
                $("#event-repeat-period").show();
            } else {
                $("#event-repeat-period").hide();
            }
        });

        if ($('#Event_is_private').val() == 1) {
            $("fieldset#private").show();
            $("fieldset#public").hide();
        }

    });
</script>

protected/views/event/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'start_date',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'end_date',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'instance_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'completed_in',array('class'=>'span5')); ?>

	<?php echo $form->textAreaRow($model,'notes',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/event/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('start_date')); ?>:</b>
	<?php echo CHtml::encode($data->start_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('end_date')); ?>:</b>
	<?php echo CHtml::encode($data->end_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('instance_id')); ?>:</b>
	<?php echo CHtml::encode($data->instance_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('completed_in')); ?>:</b>
	<?php echo CHtml::encode($data->completed_in); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('notes')); ?>:</b>
	<?php echo CHtml::encode($data->notes); ?>
	<br />


</div>

protected/views/event/admin.php
<?php $this->widget('bootstrap.widgets.TbButton', array(
    'label'=>'Create new event',
    'type'=>'success',
    'url' => Yii::app()->createUrl('event/create'),
)); ?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'event-grid',
	'dataProvider'=>$model->search(),
	'columns'=>array(
		'id',
		'start_date',
		'end_date',
		'instance_id',
		'completed_in',
		'notes',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/event/create.php
<?php
$this->menu=array(
	array('label'=>'List Event','url'=>array('index')),
	array('label'=>'Manage Event','url'=>array('admin')),
);
?>

<h1>Create Event</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model, 'archetypes' => $archetypes)); ?>

protected/views/event/index.php
<?php
$this->menu=array(
	array('label'=>'Create Event','url'=>array('create')),
	array('label'=>'Manage Event','url'=>array('admin')),
);
?>

<h1>Events</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/event/update.php
<?php
$this->menu=array(
	array('label'=>'List Event','url'=>array('index')),
	array('label'=>'Create Event','url'=>array('create')),
	array('label'=>'View Event','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Event','url'=>array('admin')),
);
?>

<h1>Update Event <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model, 'archetypes' => $archetypes)); ?>

protected/views/event/view.php
<p style="float: right">
	<?php $this->widget('bootstrap.widgets.TbButton', array(
		'label' => 'Export to Excel',
		'url' => $this->createUrl('event/export', array('event' => $model->event_id))
	)); ?>
</p>
<p>Event: <?php echo $event->instance->name; ?></p>
<p>Start time: <?php echo $event->start_date; ?></p>

<p>Members that have signed up</p>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
    'type' => 'condensed',
    'dataProvider' => $model->search(),
    'columns' => array(
        array (
            'name' => 'member.name',
            'htmlOptions' => array('style' => 'font-weight: bold;')
        ),
        array(
            'name' => 'member.avatar',
            'type' => 'image',
            'value' => 'Yii::app()->baseUrl . "/images/avatars/{$data->member->avatar}"'
        ),
        array(
            'type' => 'raw',
            'name' => 'archetype',
            'value' => 'CHtml::tag("span", array("class" => "label " . Archetype::cssClass($data->archetype)), Archetype::toText($data->archetype))',
        ),
        'notes',
        array(
            'name' => 'date_signed',
            'value' => 'Yii::app()->dateFormatter->formatDateTime(strtotime($data->date_signed))'
        ),
    ),
)); ?>