protected/controllers/EventController.php
<?php

class EventController extends Controller {
    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete', 'export'),
                'expression' => '!Yii::app()->user->isGuest && Yii::app()->user->member->role == Role::ROLE_ADMIN',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $event = $this->loadModel($id);
        $member = new EventMember('search');
        $member->event_id = $id;

        $this->render('view', array(
            'event' => $event,
            'model' => $member,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        Yii::app()->clientScript->registerCoreScript('jquery');
        Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/bootstrap-datetimepicker.min.js');
        Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/datetimepicker.css');

        $model = new Event;

        if (isset($_POST['Event'])) {
            if (isset($_POST['repeat'])) {
                for ($i = 0; $i < $_POST['number']; ++$i) {
                    $model->attributes = $_POST['Event'];
                    $startDate = new DateTime($model->start_date);
                    $startDate->add(new DateInterval("P{$i}{$_POST['period']}"));
                    $endDate = new DateTime($model->end_date);
                    $endDate->add(new DateInterval("P{$i}{$_POST['period']}"));
                    $model->start_date = $startDate->format('Y-m-d H:i:s');
                    $model->end_date = $endDate->format('Y-m-d H:i:s');
                    $archetypes = array();
                    foreach ($_POST['Arch'] as $arch)
                        $archetypes[$arch['key']] = $arch['count'];
                    $model->archetypes = $archetypes;
                    if ($model->save()) {
                        if (isset($_POST['event_members'])) {
                            foreach ($_POST['event_members'] as $memberID) {
                                $member = Member::model()->findByPk($memberID);
                                $m = new EventMember();
                                $m->event_id = $model->id;
                                $m->member_id = $memberID;
                                $m->archetype = $member->main_archetype;
                                $m->date_signed = date('Y-m-d H:i:s');
                                $m->save();
                            }
                        }
                        $model = new Event;
                    }
                }
                $this->redirect(array('admin'));
            } else {
                $model->attributes = $_POST['Event'];
                $archetypes = array();
                foreach ($_POST['Arch'] as $arch)
                    $archetypes[$arch['key']] = $arch['count'];
                $model->archetypes = $archetypes;
                if ($model->save()) {
                    if (isset($_POST['event_members'])) {
                        foreach ($_POST['event_members'] as $memberID) {
                            $member = Member::model()->findByPk($memberID);
                            $m = new EventMember();
                            $m->event_id = $model->id;
                            $m->member_id = $memberID;
                            $m->archetype = $member->main_archetype;
                            $m->date_signed = date('Y-m-d H:i:s');
                            $m->save();
                        }
                    }
                    $this->redirect(array('view', 'id' => $model->id));
                }
            }
        }

        $this->render('create', array(
            'model' => $model,
            'archetypes' => Archetype::getArray(),
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        Yii::app()->clientScript->registerCoreScript('jquery');
        Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/bootstrap-datetimepicker.min.js');
        Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/datetimepicker.css');

        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Event'])) {
            $model->attributes = $_POST['Event'];
            $archetypes = array();
            foreach ($_POST['Arch'] as $arch)
                $archetypes[$arch['key']] = $arch['count'];
            $model->archetypes = $archetypes;
            if ($model->save()) {
                if (isset($_POST['event_members'])) {
                    $model->removeAllMembers();
                    foreach ($_POST['event_members'] as $memberID) {
                        $member = Member::model()->findByPk($memberID);
                        $m = new EventMember();
                        $m->event_id = $model->id;
                        $m->member_id = $memberID;
                        $m->archetype = $member->main_archetype;
                        $m->date_signed = date('Y-m-d H:i:s');
                        $m->save();
                    }
                }
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
            'archetypes' => Archetype::getArray(),
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Event');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Event('search');
        $model->unsetAttributes();
        if (isset($_GET['Event']))
            $model->attributes = $_GET['Event'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

	public function actionExport($event) {
		$em = new EventMember();
		$em->event_id = $event;
		$this->widget('application.extensions.phpexcel.EExcelView', array(
			'dataProvider'=> $em->search(),
			'grid_mode'=>'export',
			'title'=>'Signed up members',
			'filename'=>'members',
			'stream'=>true,
			'exportType'=>'Excel2007',
			'columns'=>array(
				array (
					'name' => 'member.name',
					'htmlOptions' => array('style' => 'font-weight: bold;')
				),
				array(
					'type' => 'raw',
					'name' => 'archetype',
					'value' => 'CHtml::tag("span", array("class" => "label " . Archetype::cssClass($data->archetype)), Archetype::toText($data->archetype))',
				),
				'notes',
				array(
					'name' => 'date_signed',
					'value' => 'Yii::app()->dateFormatter->formatDateTime(strtotime($data->date_signed))'
				),
			),
		));

		Yii::app()->end();
	}

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id) {
        $model = Event::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'event-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    public function filters() {
        return array(
            'accessControl',
        );
    }

    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('login'),
                'users' => array('*'),
            ),
            array('allow',
                'users' => array('@'),
            ),
            array('deny',
                'users' => array('*'),
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        $this->render('index', array(
            'cabal' => CabalInfo::model()->find(),
            'events' => Event::model()->available()->findAll(),
        ));
    }

    public function actionSignup($id) {
        $model = new EventMember();

        if (isset($_POST['EventMember'])) {
            $model->attributes = $_POST['EventMember'];
            $model->event_id = $id;
            $model->member_id = Yii::app()->user->member->id;
            $model->date_signed = date('Y-m-d H:i:s');

            if ($model->save())
                $this->redirect(Yii::app()->createUrl('site/index'));
        }

        $event = Event::model()->findByPk($id);
        $archetypes = array();
        if ($event) {
            $signed = $event->getArchetypeMembersSigned();
            if ($signed) {
                foreach ($event->archetypes as $arch => $count) {
                    if ((isset($signed[$arch]) && $count > 0 && $signed[$arch] < $count) || (!isset($signed[$arch]) && $count > 0))
                        $archetypes[$arch] = Archetype::toText($arch);
                }
                $archetypes[Archetype::ARCHETYPE_BACKUP] = Archetype::toText(Archetype::ARCHETYPE_BACKUP);
            } else if (count($event->members) == array_sum($event->archetypes)) {
                $archetypes = array(Archetype::ARCHETYPE_BACKUP => Archetype::toText(Archetype::ARCHETYPE_BACKUP));
            } else {
                $archetypes = Archetype::getArray();
            }
        }

        $data = array(
            'success' => true,
            'body' => $this->renderPartial('_signup_form', array('model' => $model, 'availableArchetypes' => $archetypes), true, true),
        );

        header('Content-type: application/json');
        echo json_encode($data);
    }

    public function actionUnsign($id) {
        $em = EventMember::model()->findByAttributes(array(
            'event_id' => $id,
            'member_id' => Yii::app()->user->member->id,
        ))->delete();

        $this->redirect(Yii::app()->createUrl('site/index'));
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {
        if (!Yii::app()->user->isGuest)
            $this->redirect(Yii::app()->createUrl('site/index'));

        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login())
                $this->redirect(Yii::app()->user->returnUrl);
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }
}

protected/views/site/_signup_form.php
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id' => 'signup-form',
    'enableAjaxValidation' => false,
)); ?>

<?php echo $form->errorSummary($model); ?>

<?php echo $form->dropDownListRow($model, 'archetype', $availableArchetypes, array('class' => 'span5')); ?>

<hr>

<?php echo $form->textAreaRow($model, 'notes', array('rows' => 6, 'cols' => 50, 'class' => 'span5')); ?>

<div class="form-actions">
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type' => 'primary',
        'label' => 'Signup',
    )); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/views/site/index.php
<?php
/* @var $this SiteController */
?>

    <div class="row text-center">
        <h3><?php echo Yii::t('default', "Welcome to {cabal}'s event signup", array('{cabal}' => $cabal->name)); ?></h3>

        <h4><?php echo Yii::t('default', 'Select an event to signup'); ?></h4>
    </div>
<div class="row index-events">
    <p class="hint">
        Event times are adjusted to your timezone. Edit your timezone in your
        <a href="<?php echo Yii::app()->createUrl('member/update/' . Yii::app()->user->member->id); ?>">profile</a>
    </p>
<?php foreach ($events as $event) : ?>
    <?php if (!$event->is_private or ($event->is_private and $event->isUserInEvent())) : ?>
        <div class="index-event span-4">
        <h4><strong><?php echo $event->instance->name; ?></strong></h4>

        <p class="hint"><?php echo $event->notes; ?></p>
        <?php echo CHtml::image(Yii::app()->baseUrl . '/images/instances/' . $event->instance->image); ?>
        <p>Starts at <span class="event-start-date"><?php echo $event->start_date; ?></span></p>
        <?php if ($event->end_date) : ?>
            <p>Ends at <span class="event-end-date"><?php echo $event->end_date; ?></span></p>
        <?php endif; ?>
        <hr>
        <?php if ($event->is_private) : ?>
            <p><strong>Members joining</strong></p>
            <?php foreach ($event->members as $member) : ?>
                <p>
                    <?php echo CHtml::tag('span', array('class' => 'event-private-member-name'), $member->name); ?>
                    <?php echo CHtml::tag('span', array('style' => 'float: right;', 'class' => 'label ' . Archetype::cssClass($member->main_archetype)), Archetype::toText($member->main_archetype)); ?>
                </p>
            <?php endforeach; ?>
            <?php $this->widget('bootstrap.widgets.TbButton', array(
                'label' => 'Unsign',
                'type' => 'danger',
                'url' => Yii::app()->createUrl('site/unsign', array('id' => $event->id)),
            )); ?>
            <p class="hint">If you un-sign from this private event, only an officer can sign you up again.</p>
            </div>
        <?php else : ?>
            <p><strong>Classes needed</strong></p>
            <?php foreach ($event->archetypes as $arch => $count) : ?>
                <?php $mcount = $count - $event->getMembersSignedByArchetype($arch); ?>
                <p>
                    <?php if ($mcount > 0) : ?>
                        <?php echo CHtml::tag('span', array('class' => 'label ' . Archetype::cssClass($arch)), Archetype::toText($arch)); ?>
                        <?php echo CHtml::tag('span', array('class' => 'event-signed'), $mcount); ?>
                    <?php else : ?>
                        <?php echo CHtml::tag('span', array('class' => 'label'), Archetype::toText($arch)); ?>
                        <?php echo CHtml::tag('span', array('class' => 'event-no-signed'), 0); ?>
                    <?php endif; ?>
                </p>
            <?php endforeach; ?>
            <hr>
            <div class="text-center">
                <?php if (!$event->meetsRequirements()) : ?>
                    <small>You cannot sign up for this event<br>
                        because you don't meet the minimum<br>
                        QL requirements!
                    </small>
                <?php elseif (Yii::app()->user->member->hasSignedUp($event->id)) : ?>
                    <p>You are signed up for this event!</p>
                    <?php $this->widget('bootstrap.widgets.TbButton', array(
                        'label' => 'Unsign',
                        'type' => 'danger',
                        'url' => Yii::app()->createUrl('site/unsign', array('id' => $event->id)),
                    )); ?>
                <?php else : ?>
                    <?php $this->widget('bootstrap.widgets.TbButton', array(
                        'label' => 'Sign up',
                        'type' => 'primary',
                        'buttonType' => 'ajaxButton',
                        'size' => 'large',
                        'url' => Yii::app()->createUrl('site/signup', array('id' => $event->id)),
                        'ajaxOptions' => array(
                            'success' => 'function(data) {
                                if (data.success) {
                                    $("#signup-modal .modal-body p").html(data.body);
                                    $("#signup-modal .modal-header h4").html(data.header);
                                    $("#signup-modal").modal({"show": true});
                                }
                            }'
                        ),
                    )); ?>
                <?php endif; ?>
                <p class="hint"><?php echo CHtml::link('View ' . count($event->members) . ' signups for this event', Yii::app()->createUrl('event/view', array('id' => $event->id))); ?></p>
            </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endforeach; ?>
    </div>
<?php $this->beginWidget('bootstrap.widgets.TbModal', array('id' => 'signup-modal')); ?>

    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h4></h4>
    </div>

    <div class="modal-body">
        <p></p>
    </div>

<?php $this->endWidget(); ?>

protected/views/site/login.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm */
?>
<h1>Login</h1>

<div class="form">

    <?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'login-form',
        'type' => 'horizontal',
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        ),
    )); ?>

    <?php echo $form->textFieldRow($model, 'username'); ?>

    <?php echo $form->checkBoxRow($model, 'rememberMe'); ?>

    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType' => 'submit',
            'type' => 'primary',
            'label' => 'Login',
        )); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->