protected/models/Member.php
<?php

/**
 * This is the model class for table "member".
 *
 * The followings are the available columns in table 'member':
 * @property integer $id
 * @property string $name
 * @property integer $role
 * @property string $real_name
 * @property string $forum_name
 * @property string $avatar
 * @property integer $main_archetype
 * @property integer $secondary_archetype
 * @property integer $third_archetype
 * @property integer $avg_weapon_ql
 * @property integer $avg_talisman_ql
 * @property integer $avg_glyph_ql
 * @property string $chronicle_url
 * @property string $notes
 *
 * @property Event[] $events
 */
class Member extends CActiveRecord
{

    public $tempId;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Member the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'member';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return array(
            array('name, role, main_archetype, timezone_id', 'required'),
            array('role, main_archetype, secondary_archetype, third_archetype', 'numerical', 'integerOnly' => true),
            array('avg_weapon_ql, avg_talisman_ql, avg_glyph_ql', 'numerical'),
            array('name, real_name, forum_name, avatar', 'length', 'max' => 255),
            array('notes, avatar, chronicle_url', 'safe'),
            array('id, name, role, real_name, forum_name, avatar, main_archetype, secondary_archetype, third_archetype, avg_weapon_ql, avg_talisman_ql, avg_glyph_ql, notes', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        return array(
            'events' => array(self::MANY_MANY, 'Event', 'event_member(member_id, event_id)'),
            'timezone' => array(self::BELONGS_TO, 'Timezone', 'timezone_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'name' => 'Name',
            'role' => 'Role',
            'real_name' => 'Real Name',
            'forum_name' => 'Forum Name',
            'avatar' => 'Avatar',
            'main_archetype' => 'Main Class',
            'secondary_archetype' => 'Secondary Class',
            'third_archetype' => 'Third Class',
            'avg_weapon_ql' => 'Average Weapon QL',
            'avg_talisman_ql' => 'Average Talisman QL',
            'avg_glyph_ql' => 'Average Glyph QL',
            'notes' => 'Notes',
            'timezone_id' => 'Timezone',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('role', $this->role);
        $criteria->compare('real_name', $this->real_name, true);
        $criteria->compare('forum_name', $this->forum_name, true);
        $criteria->compare('avatar', $this->avatar, true);
        $criteria->compare('main_archetype', $this->main_archetype);
        $criteria->compare('secondary_archetype', $this->secondary_archetype);
        $criteria->compare('third_archetype', $this->third_archetype);
        $criteria->compare('avg_weapon_ql', $this->avg_weapon_ql);
        $criteria->compare('avg_talisman_ql', $this->avg_talisman_ql);
        $criteria->compare('avg_glyph_ql', $this->avg_glyph_ql);
        $criteria->compare('notes', $this->notes, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 50,
            )
        ));
    }

    public function beforeSave()
    {
        if ($this->avatar != 'default-avatar.png') {
            $imageP = Yii::app()->image->load(Yii::app()->basePath . "/../images/avatars/{$this->avatar}");
            $imageP->resize(50, null)->quality(100)->save(Yii::app()->basePath . "/../images/avatars/{$this->avatar}");
        }
        if (Yii::app()->user->member->role != Role::ROLE_ADMIN)
            $this->role = Role::ROLE_MEMBER;

        return parent::beforeSave();
    }

    public function beforeDelete()
    {
        $this->tempId = $this->id;
        return parent::beforeDelete();
    }

    public function afterDelete()
    {
        parent::afterDelete();
        $events = EventMember::model()->findAllByAttributes(array('member_id' => $this->tempId));
        foreach ($events as $event) {
            $event->delete();
        }
        return;
    }

    public function hasSignedUp($eventID)
    {
        return EventMember::model()->exists(
            'event_id = :event AND member_id = :member',
            array(':event' => $eventID, ':member' => $this->id)
        );
    }
}

protected/controllers/MemberController.php
<?php

class MemberController extends Controller {
    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow',
                'actions' => array('update'),
                'expression' => '!Yii::app()->user->isGuest && Yii::app()->user->member->id == $_GET["id"]'
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'expression' => '!Yii::app()->user->isGuest && Yii::app()->user->member->role == Role::ROLE_ADMIN',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Member;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Member'])) {
            $model->attributes = $_POST['Member'];
            $model->avatar = null;
            $file = CUploadedFile::getInstance($model, 'avatar');
            if ($file) {
                $file->saveAs(Yii::app()->basePath . '/../images/avatars/' . $file->name);
                $model->avatar = $file->name;
            } else {
                $model->avatar = 'default_avatar.png';
            }
            if ($model->save()) {
                Yii::app()->user->member->refresh();
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);
        $origFile = $model->avatar;

        if (isset($_POST['Member'])) {
            $model->attributes = $_POST['Member'];
            $model->avatar = null;
            $file = CUploadedFile::getInstance($model, 'avatar');
            if ($file) {
                $file->saveAs(Yii::app()->basePath . '/../images/avatars/' . $file->name);
                $model->avatar = $file->name;
            } elseif ($origFile) {
                $model->avatar = $origFile;
            } else {
                $model->avatar = 'default_avatar.png';
            }
            if ($model->save()) {
                Yii::app()->user->member->refresh();
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Member');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Member('search');
        $model->unsetAttributes(); // clear any default values
        if (isset($_GET['Member']))
            $model->attributes = $_GET['Member'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id) {
        $model = Member::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'member-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/views/member/_form.php
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id' => 'member-form',
    'enableAjaxValidation' => false,
    'htmlOptions' => array(
        'enctype' => 'multipart/form-data'
    )
)); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

<?php echo $form->textFieldRow($model, 'name', array('class' => 'span5', 'maxlength' => 255)); ?>

<?php echo $form->dropDownListRow($model, 'role', Role::getArray(), array('class' => 'span5')); ?>

<?php echo $form->textFieldRow($model, 'real_name', array('class' => 'span5', 'maxlength' => 255)); ?>

<?php echo $form->textFieldRow($model, 'forum_name', array('class' => 'span5', 'maxlength' => 255)); ?>

<?php echo $form->fileFieldRow($model, 'avatar', array('class' => 'span5', 'maxlength' => 255)); ?>

<?php echo $form->dropDownListRow($model, 'main_archetype', Archetype::getArray(), array('class' => 'span5', 'prompt' => 'Select one')); ?>

<?php echo $form->dropDownListRow($model, 'secondary_archetype', Archetype::getArray(), array('class' => 'span5', 'prompt' => 'Select one')); ?>

<?php echo $form->dropDownListRow($model, 'third_archetype', Archetype::getArray(), array('class' => 'span5', 'prompt' => 'Select one')); ?>

<?php echo $form->textFieldRow($model, 'avg_weapon_ql', array('class' => 'span5')); ?>

<?php echo $form->textFieldRow($model, 'avg_talisman_ql', array('class' => 'span5')); ?>

<?php echo $form->textFieldRow($model, 'avg_glyph_ql', array('class' => 'span5')); ?>

<?php echo $form->textFieldRow($model, 'chronicle_url', array('class' => 'span5')); ?>

<?php echo $form->dropDownListRow($model, 'timezone_id', CHtml::listData(Timezone::model()->findAll(), 'id', 'timezone'), array('class' => 'span5', 'prompt' => 'Select one')); ?>

<?php echo $form->textAreaRow($model, 'notes', array('rows' => 6, 'cols' => 50, 'class' => 'span8')); ?>

<div class="form-actions">
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type' => 'primary',
        'label' => $model->isNewRecord ? 'Create' : 'Save',
    )); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/member/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'role',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'real_name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'forum_name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'avatar',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'main_archetype',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'secondary_archetype',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'third_archetype',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'avg_weapon_ql',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'avg_talisman_ql',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'avg_glyph_ql',array('class'=>'span5')); ?>

	<?php echo $form->textAreaRow($model,'notes',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/member/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('role')); ?>:</b>
	<?php echo CHtml::encode($data->role); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('real_name')); ?>:</b>
	<?php echo CHtml::encode($data->real_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('forum_name')); ?>:</b>
	<?php echo CHtml::encode($data->forum_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('avatar')); ?>:</b>
	<?php echo CHtml::encode($data->avatar); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('main_archetype')); ?>:</b>
	<?php echo CHtml::encode($data->main_archetype); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('secondary_archetype')); ?>:</b>
	<?php echo CHtml::encode($data->secondary_archetype); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('third_archetype')); ?>:</b>
	<?php echo CHtml::encode($data->third_archetype); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('avg_weapon_ql')); ?>:</b>
	<?php echo CHtml::encode($data->avg_weapon_ql); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('avg_talisman_ql')); ?>:</b>
	<?php echo CHtml::encode($data->avg_talisman_ql); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('avg_glyph_ql')); ?>:</b>
	<?php echo CHtml::encode($data->avg_glyph_ql); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('notes')); ?>:</b>
	<?php echo CHtml::encode($data->notes); ?>
	<br />

	*/ ?>

</div>

protected/views/member/admin.php
<?php
/* @var $this MemberController */
/* @var $model Member */
$this->widget('bootstrap.widgets.TbButton', array(
    'label'=>'Add new member',
    'type'=>'success',
    'url' => Yii::app()->createUrl('member/create'),
));

$this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'member-grid',
	'dataProvider'=>$model->search(),
	'columns'=>array(
		'id',
		'name',
		array(
            'name' => 'role',
            'value' => 'Role::toText($data->role)',
        ),
		'real_name',
		'forum_name',
		array(
            'name' => 'avatar',
            'type' => 'image',
            'value' => 'Yii::app()->baseUrl . "/images/avatars/{$data->avatar}"'
        ),
        array(
            'type' => 'raw',
            'name' => 'main_archetype',
            'value' => 'CHtml::tag("span", array("class" => "label " . Archetype::cssClass($data->main_archetype)), Archetype::toText($data->main_archetype))'
        ),
        array(
            'type' => 'raw',
            'name' => 'secondary_archetype',
            'value' => 'CHtml::tag("span", array("class" => "label " . Archetype::cssClass($data->secondary_archetype)), Archetype::toText($data->secondary_archetype))'
        ),
        array(
            'type' => 'raw',
            'name' => 'third_archetype',
            'value' => 'CHtml::tag("span", array("class" => "label " . Archetype::cssClass($data->third_archetype)), Archetype::toText($data->third_archetype))'
        ),
		'avg_weapon_ql',
		'avg_talisman_ql',
		'avg_glyph_ql',
        'timezone.timezone',
		'notes',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/member/create.php
<?php
$this->menu=array(
	array('label'=>'List Member','url'=>array('index')),
	array('label'=>'Manage Member','url'=>array('admin')),
);
?>

<h1>Create Member</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/member/index.php
<?php
$this->menu=array(
	array('label'=>'Create Member','url'=>array('create')),
	array('label'=>'Manage Member','url'=>array('admin')),
);
?>

<h1>Members</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/member/update.php
<?php
$this->menu=array(
	array('label'=>'List Member','url'=>array('index')),
	array('label'=>'Create Member','url'=>array('create')),
	array('label'=>'View Member','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Member','url'=>array('admin')),
);
?>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/member/view.php
<p>
<h1><?php echo $model->name; ?></h1>
<p>
    <?php echo CHtml::image(Yii::app()->baseUrl . "/images/avatars/{$model->avatar}"); ?>
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'label' => 'Edit',
        'type' => 'success',
        'type' => 'info',
        'size' => 'small',
        'url' => Yii::app()->createUrl('member/update', array('id' => $model->id)),
        'htmlOptions' => array('style' => 'float: right;')
    )); ?>
</p>
</p>
<?php $this->widget('bootstrap.widgets.TbDetailView', array(
    'data' => $model,
    'type' => 'condensed',
    'attributes' => array(
        array(
            'name' => 'role',
            'value' => Role::toText($model->role),
        ),
        'real_name',
        'forum_name',
        array(
            'type' => 'raw',
            'name' => 'main_archetype',
            'value' => CHtml::tag("span", array("class" => "label " . Archetype::cssClass($model->main_archetype)), Archetype::toText($model->main_archetype))
        ),
        array(
            'type' => 'raw',
            'name' => 'secondary_archetype',
            'value' => CHtml::tag("span", array("class" => "label " . Archetype::cssClass($model->secondary_archetype)), Archetype::toText($model->secondary_archetype))
        ),
        array(
            'type' => 'raw',
            'name' => 'third_archetype',
            'value' => CHtml::tag("span", array("class" => "label " . Archetype::cssClass($model->third_archetype)), Archetype::toText($model->third_archetype))
        ),
        'avg_weapon_ql',
        'avg_talisman_ql',
        'avg_glyph_ql',
        array(
            'type' => 'url',
            'name' => 'chronicle_url',
        ),
        'timezone.timezone',
        'notes',
    ),
)); ?>