protected/models/Instance.php
<?php

/**
 * This is the model class for table "instance".
 *
 * The followings are the available columns in table 'instance':
 * @property integer $id
 * @property string $name
 * @property string $image
 * @property integer $min_weapon_ql
 * @property integer $min_talisman_ql
 * @property integer $min_glyph_ql
 * @property string $archetypes_needed
 * @property string $notes
 */
class Instance extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Instance the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'instance';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, image, min_weapon_ql, min_talisman_ql, min_glyph_ql', 'required'),
			array('min_weapon_ql, min_talisman_ql, min_glyph_ql', 'numerical'),
			array('name, image', 'length', 'max'=>255),
			array('notes', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, image, min_weapon_ql, min_talisman_ql, min_glyph_ql, notes', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'image' => 'Image',
			'min_weapon_ql' => 'Min Weapon Ql',
			'min_talisman_ql' => 'Min Talisman Ql',
			'min_glyph_ql' => 'Min Glyph Ql',
			'notes' => 'Notes',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('image',$this->image,true);
		$criteria->compare('min_weapon_ql',$this->min_weapon_ql);
		$criteria->compare('min_talisman_ql',$this->min_talisman_ql);
		$criteria->compare('min_glyph_ql',$this->min_glyph_ql);
		$criteria->compare('notes',$this->notes,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/InstanceController.php
<?php

class InstanceController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'expression' => '!Yii::app()->user->isGuest && Yii::app()->user->member->role == Role::ROLE_ADMIN',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Instance;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Instance']))
		{
			$model->attributes=$_POST['Instance'];
            $model->image = null;
            $file = CUploadedFile::getInstance($model, 'image');
            if ($file) {
                $file->saveAs(Yii::app()->basePath . '/../images/instances/' . $file->name);
                $model->image = $file->name;
            }
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Instance']))
		{
            $model->attributes=$_POST['Instance'];
            $model->image = null;
            $file = CUploadedFile::getInstance($model, 'image');
            if ($file) {
                $file->saveAs(Yii::app()->basePath . '/../images/instances/' . $file->name);
                $model->image = $file->name;
            }
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Instance');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Instance('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Instance']))
			$model->attributes=$_GET['Instance'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Instance::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='instance-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/instance/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'instance-form',
	'enableAjaxValidation'=>false,
    'htmlOptions' => array(
        'enctype' => 'multipart/form-data',
    ),
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->fileFieldRow($model,'image',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'min_weapon_ql',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'min_talisman_ql',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'min_glyph_ql',array('class'=>'span5')); ?>

	<?php echo $form->textAreaRow($model,'notes',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/instance/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'image',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'min_weapon_ql',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'min_talisman_ql',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'min_glyph_ql',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'archetypes_needed',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textAreaRow($model,'notes',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/instance/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('image')); ?>:</b>
	<?php echo CHtml::encode($data->image); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('min_weapon_ql')); ?>:</b>
	<?php echo CHtml::encode($data->min_weapon_ql); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('min_talisman_ql')); ?>:</b>
	<?php echo CHtml::encode($data->min_talisman_ql); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('min_glyph_ql')); ?>:</b>
	<?php echo CHtml::encode($data->min_glyph_ql); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('archetypes_needed')); ?>:</b>
	<?php echo CHtml::encode($data->archetypes_needed); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('notes')); ?>:</b>
	<?php echo CHtml::encode($data->notes); ?>
	<br />

	*/ ?>

</div>

protected/views/instance/admin.php
<?php $this->widget('bootstrap.widgets.TbButton', array(
    'label'=>'Create new instance',
    'type'=>'success',
    'url' => Yii::app()->createUrl('instance/create'),
)); ?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'instance-grid',
	'dataProvider'=>$model->search(),
	'columns'=>array(
		'id',
		'name',
		'image',
		'min_weapon_ql',
		'min_talisman_ql',
		'min_glyph_ql',
		'notes',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/instance/create.php
<?php
$this->menu=array(
	array('label'=>'List Instance','url'=>array('index')),
	array('label'=>'Manage Instance','url'=>array('admin')),
);
?>

<h1>Create Instance</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/instance/index.php
<?php

$this->menu=array(
	array('label'=>'Create Instance','url'=>array('create')),
	array('label'=>'Manage Instance','url'=>array('admin')),
);
?>

<h1>Instances</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/instance/update.php
<?php
$this->menu=array(
	array('label'=>'List Instance','url'=>array('index')),
	array('label'=>'Create Instance','url'=>array('create')),
	array('label'=>'View Instance','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Instance','url'=>array('admin')),
);
?>

<h1>Update Instance <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/instance/view.php
<?php
$this->menu=array(
	array('label'=>'List Instance','url'=>array('index')),
	array('label'=>'Create Instance','url'=>array('create')),
	array('label'=>'Update Instance','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete Instance','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Instance','url'=>array('admin')),
);
?>
<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'image',
		'min_weapon_ql',
		'min_talisman_ql',
		'min_glyph_ql',
		'notes',
	),
)); ?>